// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsrA2omKhUfr1mnrLhyR7SNBUXz3uPy10',
    appId: '1:641405620761:web:1985556a7c6d9f304a9088',
    messagingSenderId: '641405620761',
    projectId: 'tagfalter-monitoring-bb766',
    authDomain: 'tagfalter-monitoring-bb766.firebaseapp.com',
    storageBucket: 'tagfalter-monitoring-bb766.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0P1uxxZM3sbi1_rXLitN2sQuv4Tr-pOI',
    appId: '1:641405620761:android:e39a93cf076f94f74a9088',
    messagingSenderId: '641405620761',
    projectId: 'tagfalter-monitoring-bb766',
    storageBucket: 'tagfalter-monitoring-bb766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRz9WadOa_VKCG-eiL5PIHosHrIZ8wzpM',
    appId: '1:641405620761:ios:e91c32fae1e6310d4a9088',
    messagingSenderId: '641405620761',
    projectId: 'tagfalter-monitoring-bb766',
    storageBucket: 'tagfalter-monitoring-bb766.appspot.com',
    iosBundleId: 'com.example.butterflyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRz9WadOa_VKCG-eiL5PIHosHrIZ8wzpM',
    appId: '1:641405620761:ios:e91c32fae1e6310d4a9088',
    messagingSenderId: '641405620761',
    projectId: 'tagfalter-monitoring-bb766',
    storageBucket: 'tagfalter-monitoring-bb766.appspot.com',
    iosBundleId: 'com.example.butterflyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsrA2omKhUfr1mnrLhyR7SNBUXz3uPy10',
    appId: '1:641405620761:web:48ca2bc025c791d04a9088',
    messagingSenderId: '641405620761',
    projectId: 'tagfalter-monitoring-bb766',
    authDomain: 'tagfalter-monitoring-bb766.firebaseapp.com',
    storageBucket: 'tagfalter-monitoring-bb766.appspot.com',
  );
}
